spring.application.name=api-gateway
server.port=9090

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

# Spring Cloud Gateway + Eureka
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true

# Actuator
management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=read-only
management.info.env.enabled=true

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://127.0.0.1:9096/realms/novabank/protocol/openid-connect/certs